# Configuration file for slurm plugin (Snakemake >8.0.0) for Rackham cluster at UPPMAX
# Last modified: tor jun 27, 2024  05:24
# Sign: JN
# Adapted from https://github.com/NBISweden/GenErode
# Links: https://www.uu.se/en/centre/uppmax/resources/clusters/rackham
# https://snakemake.github.io/snakemake-plugin-catalog/plugins/executor/slurm.html

# snakemake CLI flags
executor: slurm
jobs: 200
printshellcmds: true
software-deployment-method: apptainer

# slurm resources
## Default-resources: applied to all jobs, overruled by resources defined below for jobs
default-resources:
  slurm_partition: "core"
  slurm_account: "#SNICACCOUNT#" # Update this to your slurm account
  runtime: 45                    # Default runtime in minutes(!)
  mem_mb: 6400                   # Corresponds to amount of RAM for each core on a Rackham default compute node (total nodes=20)
  cpus_per_task: 1               # Number of "threads" per task, corresponds to 6.4 GB RAM

## set-threads: Map rule names to threads
set-threads:
  OO1_convert_fas: 1
  OO2_fasta_to_stockholm: 1
  OO3_create_hmms: 1
  OO4_cat_reference_fas: 1
  OO5_split_genome_fasta: 8
  OO6_make_genome_plast_db: 1
  OO7_run_plast: 20
  OO8_get_scaffold_ids: 1
  OO9_get_reference_ids: 1
  O10_select_scaffolds: 1
  O11_split_list_of_hmms: 1
  O12_concatente_chunk_hmms: 1
  O13_run_hmmpress: 1
  O14_run_hmmer: 2
  O15_concatenate_hmmer_out: 1
  O16_parse_hmmer: 1
  O17_gather_genes: 1
  O18_compress_hmmer_out: 8

## set-resources: Map rule names to resources in general
set-resources:
  # rulename:
  #   runtime: xxxxx (in minutes? Or "D-HH:MM:SS"?)
  #   mem_mb: xxxx (multiply 6400 with cpus_per_task)
  #   cpus_per_task: xx
  # OO1_convert_fas:
  #   runtime: 
  #   mem_mb: 
  #   cpus_per_task: 1
  # OO2_fasta_to_stockholm:
  #   runtime: 
  #   mem_mb: 
  #   cpus_per_task: 1
  # OO3_create_hmms: 
  #   runtime: 
  #   mem_mb: 
  #   cpus_per_task: 1
  # OO4_cat_reference_fas:
  #   runtime: 
  #   mem_mb: 
  #   cpus_per_task: 1
  OO5_split_genome_fasta:
    runtime: 45
    mem_mb: 51200
    cpus_per_task: 8
  # OO6_make_genome_plast_db:
  #   runtime: 
  #   mem_mb: 
  #   cpus_per_task: 1
  OO7_run_plast:
    runtime: 300
    mem_mb: 128000
    cpus_per_task: 20
  # OO8_get_scaffold_ids:
  #   runtime: 
  #   mem_mb: 
  #   cpus_per_task: 1
  # OO9_get_reference_ids:
  #   runtime: 
  #   mem_mb: 
  #   cpus_per_task: 1
  # O10_select_scaffolds:
  #   runtime: 
  #   mem_mb: 
  #   cpus_per_task: 1
  # O11_split_list_of_hmms:
  #   runtime: 
  #   mem_mb: 
  #   cpus_per_task: 1
  # O12_concatente_chunk_hmms:
  #   runtime: 
  #   mem_mb: 
  #   cpus_per_task: 1
  # O13_run_hmmpress:
  #   runtime: 
  #   mem_mb: 
  #   cpus_per_task: 1
  O14_run_hmmer: 2
    runtime: 5760
    mem_mb: 12800
    cpus_per_task: 2
  # O15_concatenate_hmmer_out:
  #   runtime: 
  #   mem_mb: 
  #   cpus_per_task: 1
  # O16_parse_hmmer:
  #   runtime: 
  #   mem_mb: 
  #   cpus_per_task: 1
  # O17_gather_genes:
  #   runtime: 
  #   mem_mb: 
  #   cpus_per_task: 1
  O18_compress_hmmer_out:
    runtime: 45
    mem_mb: 51200
    cpus_per_task: 8
