__default__:
  # exchange <snic1234-56-7> with your SLURM account id below
  account: snic2020-15-97
  partition: core
  time: 00:14:00
  cpus-per-task: 1

  # directories for slurm logs (no need to change these)
  output: "slurm/logs/{rule}.{wildcards}.out"
  error: "slurm/err/{rule}.{wildcards}.err"
