# Set defaults for birdscanner2 rules on cluster.
# Last modified: mån okt 19, 2020  11:24
# Sign: JN
# Notes: Exceptions are specified below.
# Threads are given per tool, and are specified in config/config.yaml
# IMPORTANT: Adjust the account number below.

__default__:
  account: "#SNICACCOUNT#"
  partition: core
  time: 14
  cpus-per-task: 1
  output: "slurm/stdout/{rule}.{wildcards}.out"
  error: "slurm/stderr/{rule}.{wildcards}.err"

# This job takes between 0.01 and 10 secs
# and the software runs on a single cpu (not multi-threading).
# The job will be repeated, however, for thousands of files.
#OO1_convert_fas:
#    time: 10
#
### repeated thousands of times
#OO2_fasta_to_stockholm:
#    time: 10
#
### repeated thousands of times
#OO3_create_hmms:
#    time: 10
#
#OO4_cat_reference_fas:
#    time: 10   

#OO5_split_genome_fasta:
#    time: 10

#OO6_make_genome_plast_db:
#    time: 10

##### 10,000 secs
OO7_run_plast:
    time: 700

# local rule?
#OO8_get_scaffold_ids:
#    time: 10

# local rule?
#OO9_get_reference_ids:
#    time: 10

# local rule?
#O10_select_scaffolds:
#    time: 10

# local rule?
#O11_select_hmms:
#    time: 10

#O12_run_hmmpress:
#    time: 10

##### 100,000 secs
O13_run_hmmer:
    time: 2000

#O14_parse_hmmer:
#    time: 10

#O15_gather_genes:
#    time: 10

#O16_compress_hmmer_out:
#    time: 10

