# Set defaults for birdscanner2 rules on cluster.
# Last modified: ons okt 14, 2020  03:06
# Sign: JN
# Notes: Exceptions are specified below.
# Threads are given per tool, and are specifies in config/config.yaml

__default__:
  # Replace <snic1234-56-7> with your SLURM account below
  account: snic2020-15-97
  partition: core
  time: "00:14:00"
  cpus-per-task: 1

  # directories for slurm logs (no need to change these)
  #output: "slurm/logs/{rule}.{wildcards}.out"
  #error: "slurm/err/{rule}.{wildcards}.err"

# This job takes between 0.01 and 10 secs
# and the software runs on a single cpu (not multi-threading).
# The job will be repeated, however, for thousands of files.
#OO1_convert_fas:
#    time: 00:10:00
#    n: 1
#
#OO2_fasta_to_stockholm:
#    time: 00:10:00     ### repeated thousands of times
#    n: 1
#
#OO3_create_hmms:
#    time: 00:10:00  ### repeated thousands of times
#    n: 1
#
#OO4_cat_reference_fas:
#    time: 00:10:00   
#    n: 1

#OO5_split_genome_fasta:
#    time: 00:10:00

#OO6_make_genome_plast_db:
#    time: 00:10:00

##### 10,000 secs
OO7_run_plast:
    time: "04:00:00"

# local rule?
#OO8_get_scaffold_ids:
#    time: 00:10:00

# local rule?
#OO9_get_reference_ids:
#    time: 00:10:00

# local rule?
#O10_select_scaffolds:
#    time: 00:10:00

# local rule?
#O11_select_hmms:
#    time: 00:10:00

#O12_run_hmmpress:
#    time: 00:10:00

##### 100,000 secs
O13_run_hmmer:
    time: "2-00:00:00"

#O14_parse_hmmer:
#    time: 00:10:00

#O15_gather_genes:
#    time: 00:10:00

#O16_compress_hmmer_out:
#    time: 00:10:00

