# Config file for birdscanner2
# Last modified: tis nov 03, 2020  05:27
# Sign: JN

# Reference input is DNA (True) or Protein (False).
#Reference_is_DNA: True
# Genome input is DNA (True) or Protein (False)
#Genome_is_DNA: True
# Ad hoc setting of type-specific variables
type:
    dbtype: "nucl"
    plastprog: "plastn"
    hmmbuildtype: "--dna"
    hmmerprog: "nhmmer"

# Gather genes in the end (if more than one genome)
#Gathergenes: True

# Length filter for rule OO6_get_scaffold_ids, OO7_get_reference_ids
lengthfilter:
    min: "50"

# Splitfast. 100000 is maximum for plast.
splitfast:
    max: "1000000"

# Plast
plast:
    maxhitperquery: "1"
    bargraph: "-bargraph"
    threads: 10

# Makeblastdb
makeblastdb:
    parseseqids: "-parse_seqids"

# Blastcmd
blastdbcmd:
    outfmt: "%f"

# Hmmer
hmmer:
    outfmt: "--notextw --noali"
    threads: 10

# Parsehmmer
parsehmmer:
    stats: "--stats"

# Pigz
pigz:
    threads: 8

