# Config file for birdscanner2
# Last modified: tor jun 27, 2024  05:27
# Sign: JN
# Note: if run on slurm, make sure threads are matched
# with the settings in the slurm/config.yaml file.

# Reference input is DNA (True) or Protein (False).
#Reference_is_DNA: True

# Genome input is DNA (True) or Protein (False)
#Genome_is_DNA: True

# Gather genes in the end (if more than one genome)
#Gathergenes: True

# Ad hoc setting of type-specific variables
type:
  dbtype: "nucl"
  plastprog: "plastn"
  hmmbuildtype: "--dna"
  hmmerprog: "nhmmer"

# Length filter for rule OO8_get_scaffold_ids, OO9_get_reference_ids
lengthfilter:
  min: "50"

# Max length (-m) for splitfast. 100000 is maximum for plast.
splitfast:
  max: "1000000"

# Split hmms in chunks of size chunks
split:
  chunks: "50"

# Plast
plast:
  maxhitperquery: "1"
  bargraph: "-bargraph"
  threads: 20

# Makeblastdb
makeblastdb:
  parseseqids: "-parse_seqids"

# Blastcmd
blastdbcmd:
  outfmt: "%f"

# Hmmerbuild. Could potentially set threads to higher.
hmmbuild:
  threads: 1

# Hmmer
hmmer:
  outfmt: "--notextw --noali"
  threads: 2

# Parsehmmer
parsehmmer:
  stats: "--stats"

# Pigz
pigz:
  threads: 8

